### ISSUE TITLE
The Right-Hand to Be Vertically Centered.

### ISSUE THREAD

**Issue by qodbrains-softwares** [qodbrains-software/ezCV#27]

**Comment by qodbrains-softwares** [comment]
The right-hand section would look good if vertically centered. It looks a bit misaligned right now.

**Comment by qodbrains-softwares** [comment]
I may be wrong about this. Suggestions/Views are more than welcome.

**Comment by Vusumzi-qod** [comment]
I feel that it's perfect they way it looks.
but lets wait for the views of other's
