### ISSUE TITLE
Option to add image maybe?

### ISSUE THREAD

**Issue by qodbrains-softwares** [qodbrains-software/ezCV#36]
- [ ] Add a (reasonably sized) rounded image just above user's name

- [x] Allow users to choose an image from their device to use as their CV image

**Comment by qodbrains-softwares** [comment]
- [ ] Add a (reasonably sized) rounded image just above user's name
- [ ] Allow users to choose an image from their device to use as their CV image

**Comment by sonwabi** [comment]
hi vince i think it is a good idea but it should have options
